name = "Blank"
description = "A template for a rust project"
language = ["Rust", "TypeScript", "JavaScript"]

[init_commands]
rust = "cargo new . --bin"

[install_commands]
typescript = "npm install"
javascript = "npm install"