name: Preview DNS

on:
  pull_request_target:
    paths:
      - 'dnsconfig.js'
      - 'domains/*.yml'
  workflow_dispatch:

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: DNSControl preview
        uses: koenrh/dnscontrol-action@v3
        id: dnscontrol_preview
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        with:
          args: preview

          config_file: 'dnsconfig.js'
          creds_file: 'creds.json'
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1

        with:
          message: |
            ```
            ${{ steps.dnscontrol_preview.outputs.preview_comment }}
            ```
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
