name: Check DNS

on:
  pull_request_target:
    paths:
      - 'domains/*.yml'
      - 'dnsconfig.js'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: DNSControl check
        uses: koenrh/dnscontrol-action@v3
        with:
          args: check

          config_file: 'dnsconfig.js'
